#pragma once

#include <RTNeural/RTNeural.h>

#include <array>
#include <functional>
#include <limits>
#include <memory>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "geometry_msgs/msg/pose.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "rclcpp/subscription.hpp"
#include "rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "realtime_tools/realtime_buffer.h"
#include "realtime_tools/realtime_publisher.h"
#include "controller_manager_msgs/srv/switch_controller.hpp"
#include "sensor_msgs/msg/joy.hpp"
#include "std_msgs/msg/empty.hpp"
#include "std_msgs/msg/float32.hpp"
#include "std_msgs/msg/float32_multi_array.hpp"
#include "std_msgs/msg/string.hpp"
#include "tf2/LinearMath/Matrix3x3.h"
#include "tf2/LinearMath/Quaternion.h"
#include "neural_controller/command_filter.hpp"
#include "neural_controller/gait_reference_json.hpp"
#include "neural_controller/obs_spec.hpp"
#include "neural_controller/trick_motion.hpp"
// auto-generated by generate_parameter_library
// Prefer the namespaced header. Newer generate_parameter_library releases also
// emit a deprecated top-level "neural_controller_parameters.hpp" by concatenating
// the previous file with the new one, so after a parameters.yaml change (which
// install.py makes) it holds two copies of every definition and the compile dies
// with redefinition errors. Older releases (older Pupper images) only generate the
// top-level header, written fresh each time, so fall back to it there.
#if __has_include("neural_controller/neural_controller_parameters.hpp")
#include "neural_controller/neural_controller_parameters.hpp"
#else
#include "neural_controller_parameters.hpp"
#endif

namespace neural_controller {

template <typename T>
bool contains_nan(const T &container) {
  return std::any_of(container.begin(), container.end(),
                     [](double val) { return std::isnan(val); });
}

class NeuralController : public controller_interface::ControllerInterface {
 public:
  NeuralController();

  ~NeuralController() = default;

  controller_interface::InterfaceConfiguration command_interface_configuration() const override;

  controller_interface::InterfaceConfiguration state_interface_configuration() const override;

  controller_interface::CallbackReturn on_init() override;

  controller_interface::CallbackReturn on_configure(
      const rclcpp_lifecycle::State &previous_state) override;

  controller_interface::CallbackReturn on_activate(
      const rclcpp_lifecycle::State &previous_state) override;

  controller_interface::CallbackReturn on_deactivate(
      const rclcpp_lifecycle::State &previous_state) override;

  controller_interface::CallbackReturn on_error(
      const rclcpp_lifecycle::State &previous_state) override;

  controller_interface::return_type update(const rclcpp::Time &time,
                                           const rclcpp::Duration &period) override;

 protected:
  bool check_param_vector_size();

  static constexpr int kActionSize = 12;

  // The frame layout, resolved at load from the policy JSON's "obs_spec" block
  // (contract v2) or from the legacy implicit 36/48-dim layouts. Every
  // observation write in update() goes through these offsets, so a retrained
  // policy with a different layout deploys with no controller change.
  ObsLayout obs_layout_;

  // Frame size of this policy (obs_layout_.frame_size, kept as a member for
  // the history rotation and sizing).
  int single_observation_size_ = 0;

  // Gait reference tables, empty (and unused) for non-gait policies.
  GaitReference gait_;
  bool use_gait_reference_ = false;

  // MixedGaitsJump: a jump slot insertable into the mixed reference on a
  // button press (game mode). Coexists with gait_. Two pending starts, like
  // training's schedule tensor; +inf = none.
  JumpSlot jump_slot_;
  bool use_jump_slot_ = false;
  std::array<double, 2> slot_starts_{{std::numeric_limits<double>::infinity(),
                                      std::numeric_limits<double>::infinity()}};
  // Per-slot running-hop latch: -1 until the slot's first active step, then
  // 1 (hop) or 0 (jump) for the rest of it. See JumpSlot::hop_speed.
  std::array<int, 2> slot_hop_{{-1, -1}};
  bool slot_button_prev_ = true;

  // L1+R1 chord: switch to cfg's chord_partner controller (game-mode toggle).
  // Detection and the (non-realtime) service call happen in the joy callback.
  rclcpp::Client<controller_manager_msgs::srv::SwitchController>::SharedPtr
      chord_client_ = nullptr;
  bool chord_prev_ = true;
  static constexpr int kChordButtonA = 4;  // L1
  static constexpr int kChordButtonB = 5;  // R1

  // Teleop command clamp and IMU-yaw heading hold, both from the policy JSON
  // (a gait policy with no heading_hold block still gets the validated kp-1.0
  // default hold; see on_configure). Applied to the command before the
  // observation and the gait reference see it, exactly as in training.
  CommandClip command_clip_;
  HeadingHold heading_hold_;

  // Trick (motion-tracking) policies: the reference motion the policy tracks,
  // played on the wall clock once the policy has faded in. The reference yaw is
  // aligned to the robot's heading on the first update after activation.
  TrickMotion trick_;
  ClipPlayer clip_player_;
  bool use_trick_ = false;
  // Clip requests (~/clip, a clip name) and the current clip (~/clip_status).
  realtime_tools::RealtimeBuffer<std::shared_ptr<std_msgs::msg::String>> rt_clip_request_ptr_;
  rclcpp::Subscription<std_msgs::msg::String>::SharedPtr clip_subscriber_ = nullptr;
  const std_msgs::msg::String *last_clip_request_ = nullptr;
  rclcpp::Publisher<std_msgs::msg::String>::SharedPtr clip_status_publisher_ = nullptr;
  std::shared_ptr<realtime_tools::RealtimePublisher<std_msgs::msg::String>>
      rt_clip_status_publisher_ = nullptr;
  bool trick_yaw_set_ = false;
  double trick_yaw_offset_ = 0.0;

  std::shared_ptr<RTNeural::Model<float>> model_;

  std::shared_ptr<ParamListener> param_listener_;
  Params params_;

  // Observation vector. Size is determined at runtime by the observation history parameter
  std::vector<float> observation_ = {};

  // Action vector
  std::array<float, kActionSize> action_ = {};

  // Initial joint positions
  std::array<double, kActionSize> init_joint_pos_ = {};

  // Command velocities
  float cmd_x_vel_ = 0;
  float cmd_y_vel_ = 0;
  float cmd_yaw_vel_ = 0;

  // Command body orientation
  tf2::Vector3 desired_world_z_in_body_frame_ = tf2::Vector3(0, 0, 1);

  // Map from joint names to command types to command interfaces
  std::map<
      std::string,
      std::map<std::string, std::reference_wrapper<hardware_interface::LoanedCommandInterface>>>
      command_interfaces_map_;

  // Map from joint/sensor names to state types to state interfaces
  std::map<std::string,
           std::map<std::string, std::reference_wrapper<hardware_interface::LoanedStateInterface>>>
      state_interfaces_map_;

  // Realtime buffers for command and emergency stop subscriptions
  realtime_tools::RealtimeBuffer<std::shared_ptr<geometry_msgs::msg::Twist>> rt_cmd_vel_ptr_;
  rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr cmd_vel_subscriber_ = nullptr;

  realtime_tools::RealtimeBuffer<std::shared_ptr<geometry_msgs::msg::Pose>> rt_cmd_pose_ptr_;
  rclcpp::Subscription<geometry_msgs::msg::Pose>::SharedPtr cmd_pose_subscriber_ = nullptr;

  rclcpp::Subscription<std_msgs::msg::Empty>::SharedPtr emergency_stop_subscriber_ = nullptr;
  rclcpp::Subscription<std_msgs::msg::Empty>::SharedPtr emergency_stop_reset_subscriber_ = nullptr;

  // Gamepad, for the jump trigger. Only subscribed when the policy carries a
  // jump reference.
  realtime_tools::RealtimeBuffer<std::shared_ptr<sensor_msgs::msg::Joy>> rt_joy_ptr_;
  rclcpp::Subscription<sensor_msgs::msg::Joy>::SharedPtr joy_subscriber_ = nullptr;

  // Reference tricks (params reference_tricks): a joint-offset table played once
  // through the jump-slot overlay on the running policy, e.g. its jump reference.
  realtime_tools::RealtimeBuffer<std::shared_ptr<std_msgs::msg::Float32MultiArray>>
      rt_reference_trick_ptr_;
  rclcpp::Subscription<std_msgs::msg::Float32MultiArray>::SharedPtr
      reference_trick_subscriber_ = nullptr;
  const std_msgs::msg::Float32MultiArray *last_reference_trick_ = nullptr;

  // Alias message types for future improvements
  using ActionMsg = std_msgs::msg::Float32MultiArray;
  using ObservationMsg = std_msgs::msg::Float32MultiArray;

  // Publishers
  std::shared_ptr<realtime_tools::RealtimePublisher<ActionMsg>> rt_policy_output_publisher_ =
      nullptr;
  rclcpp::Publisher<ActionMsg>::SharedPtr policy_output_publisher_ = nullptr;

  std::shared_ptr<realtime_tools::RealtimePublisher<ActionMsg>> rt_position_command_publisher_ =
      nullptr;
  rclcpp::Publisher<ActionMsg>::SharedPtr position_command_publisher_ = nullptr;

  // Observation publisher
  std::shared_ptr<realtime_tools::RealtimePublisher<ObservationMsg>> rt_observation_publisher_ =
      nullptr;
  rclcpp::Publisher<ObservationMsg>::SharedPtr observation_publisher_ = nullptr;

  // IMU latency
  std::shared_ptr<realtime_tools::RealtimePublisher<std_msgs::msg::Float32>>
      rt_imu_latency_publisher_ = nullptr;
  rclcpp::Publisher<std_msgs::msg::Float32>::SharedPtr imu_latency_publisher_ = nullptr;

  // Policy inference time
  std::shared_ptr<realtime_tools::RealtimePublisher<std_msgs::msg::Float32>>
      rt_policy_inference_latency_publisher_ = nullptr;
  rclcpp::Publisher<std_msgs::msg::Float32>::SharedPtr policy_inference_latency_publisher_ =
      nullptr;

  rclcpp::Time init_time_;

  int repeat_action_counter_;

  bool estop_active_ = false;
};

}  // namespace neural_controller
